cmake_minimum_required(VERSION 3.13)
project(llvm)

# Включаем все поддиректории
add_subdirectory(clang)
add_subdirectory(bolt)
add_subdirectory(lld)
add_subdirectory(flang)
add_subdirectory(flang-rt)
add_subdirectory(libc)
add_subdirectory(libclc)
add_subdirectory(libcxx)
add_subdirectory(libcxxabi)
add_subdirectory(libunwind)
add_subdirectory(lldb)
add_subdirectory(llvm)
add_subdirectory(mlir)
add_subdirectory(offload)
add_subdirectory(openmp)
add_subdirectory(polly)
